### ISSUE TITLE
App unable to select screen shot images for cropping.

### ISSUE THREAD

**Issue by cckole** [k3b/LosslessJpgCrop#12]
### Description
I wanted to crop a screen shot image, so I launched the app and opted to select the image I wanted to crop, but all the images in the screen shot folder were faded. I tried clicking on the screen shot images to select one for cropping, but all to no avail.

### Expected behaviour
My expectations was to be able to select any screen shot images for cropping.

### Steps to reproduce

After launching the app

- click on screen shot in the android file manager and try to select any image. You wouldn't be able to. You will notice that all the screen shot images are faded,thereby making them unclickable. 

- Device used: Techno spark k7
O.S: Android 7.0

### Reproducing the behavior

https://youtu.be/Sj7Z_Pwkawo

**Comment by k3b** [comment]
Does your android create screenshots as jpg image?

My android-7.1 makes screenshots in png image format. llCrop only works for jpg

**Comment by cckole** [comment]
It's in png format.
