### ISSUE TITLE
File name displayed for rename, but cropped image wasn't displayed 

### ISSUE THREAD

**Issue by cckole** [k3b/LosslessJpgCrop#13]
### Description

I selected a picture and cropped it after which I click the save icon to save it. Only the file name was shown and highlighted for me to rename in an empty folder. There was no traces of the image I cropped.

### Expected behaviour

My expectations was to see the cropped picture in the folder after saving it.

### Reproducing the behavior

After launching the app
- Select a picture in the file manager
- Crop the picture and click on the save icon at the top right side
- You will notice an empty folder with the file name highlighted for rename.

### Device used
- Techno spark k7
- O S: Android 7.0
### Reproducing the behavior
https://youtu.be/RxjMV0HVIKs

**Comment by k3b** [comment]
From your video: You cannot save an image into the "recent" virtual directory.

You have to select a folder where you want to save the image to from the "hamburger" menu in the upper left corner

**Comment by cckole** [comment]
Yes I succeded. That's great. You can close the issue. Thank you
