### ISSUE TITLE
Missing errormessage display: Save option not responding whenever cropped images to be saved to phone drive

### ISSUE THREAD

**Issue by abdul-qudus** [k3b/LosslessJpgCrop#14]
When I pick an image from my phone file, then after successful cropping. I tried saving it to my phone drive. But unfortunately the save option is yet to respond.
# How to produce

1. Open app
2. Select image from phone file. E.g download, images, etc
3. Then make successful cropping.
4. Try saving to phone drive after editing, save option won't respond.

**Comment by k3b** [comment]
The app closes after successfully writing the crop. If the app does not close there was some error.

TODO: I need to display some errormessage if save fails.

Thanks for pointing me to missing errordisplay

**Comment by k3b** [comment]
In v1.1.1: may be fixed or at least we get a displayed error message
