### ISSUE TITLE
Addition of fixed dimension, modifyable dimensions to IICrop

### ISSUE THREAD

**Issue by zoneboy** [k3b/LosslessJpgCrop#15]
# Introduction

IICrop (Loss Less) is an android application that helps to remove unwanted areas in a photo. It crops the image while ensuring there is no loss of the image quality.

# Component
My suggestion is on the
* Photo edit interface

# Proposal

> IICrop is a cool application that is used to edit unwanted parts of a photo without losing any of the original image quality. I still believe the application can still be improved.

* **Fixed dimensions –** I suggest the addition of fixed dimension when cropping the image. Currently, IICrop only have a free-form cropping. I propose the addition of 3 or more fixed dimensions that can easily be selected without any more alterations.

* **Editable dimensions –** The editable dimensions gives users the opportunity to specify the exact specification they want. This is one important feature that will improve the application. Users can enter the figures they want the dimension to be. 

* <strike>**Share edited photos ** This is a basic feature yet important one. The edited feature should be able to be shared to other users or other applications right inside IICrop.</strike>Implemented in #2.

# Mockups/Examples

![Comb20052019121915.jpg](https://cdn.steemitimages.com/DQmYHouP5D6dSn1FnGwdkVomzyQFDwUakVoH2bsBhcmHzRC/Comb20052019121915.jpg)

This is how I want the fixed dimension to be modified. you can see that the dimensions are already predefined and you just have to choose them. 

![Comb20052019121945.jpg](https://cdn.steemitimages.com/DQmRQJzqZUCrKVJqssZEWuytMFrV7fLHqNRHwBN4in7gF2t/Comb20052019121945.jpg)

The editable dimension should be modified like this. The user can input the figures right in the blue box which will automatically give the shape.

![20190520_123134.jpg](https://cdn.steemitimages.com/DQmfUxPwg6Wof5wMBVBne8N3LME5ACKkQo2RVBcsvAQGqzp/20190520_123134.jpg)

This is the Share function that will allow sending of the edited photo right inside the application.

# Benefits

**Fixed dimensions –** This is a very important feature that will improve the application. It will allow users to select from a predefined dimension. This will save time and stress spent in adjusting the free-form to crop an image. For example, a user who want to get a perfect square or an inverted rectangle crop will spent minutes adjusting. Instead of wasting time to adjust, the user can simply select from the predefined dimensions and apply to the photograph. It is simple when trying to get a kind of passport photograph dimension and so on.

**Editable dimensions-** This is different from the free-form crop because users can input whatever size they want. This will help when trying to get an actual specification. Instead of adjusting and trying to guess if you got the specifications right, you can just input the figures and the crop shape pops up. This is particularly useful for users who need certain dimensions for an online registration.

<strike>**Share edited photos -** The most common reason we crop unwanted parts out of a photo is to share them with who needs it. The ability to share the edited photos right inside the application will save time and stress. You are cropping a photo so you can send to a friend on WhatsApp or Facebook. It is really stressful when you have to navigate to your phone gallery just to send when you could have done that right inside the application. It saves time and eliminates stress.</strike>

# Conclusion

This features when implemented will greatly improve the application. It will let the application to be a more complete one as users can perform all the functions in it without looking elsewhere. This will increase the userbase and also change the way it is utilized.

**Comment by k3b** [comment]
Share is already implemented:
if you start llCrop from a gallery-app select edit and select llCrop as target. 
See https://github.com/k3b/LosslessJpgCrop/issues/2 .

Maybe i should also add the share button if llCrop is started in edit mode.

For my own usecases i currently have no need for certain croping aspect rations (ie square = 1/1) therefore i will not implement it myself.

If someone is willing to implement this i am happy to accept merge requests.

**Comment by k3b** [comment]
May be as an easy to implement compromise: somebody can add a statusbar that shows the current selection dimension and additional text if the rectangle matche 1*1, 7*10, 9*13, .....

However this is only an aproximation because lossless only works if width and hight are a multible of 8

**Comment by osirisinferi** [comment]
For photos, you'd like to **lock** the aspect ratio. I'm missing this feature very much. That much, that this application doesn't meet my demands and I'll have to resort to lossy cropping again.

**Comment by robbbbit** [comment]
This is exactly what I am also looking for. Please, if possible, implement this function.

**Comment by CaTeNdrE** [comment]
+1
My biggest pain with Android photo editors is the inability to enter dimensions.  

Feels like I have a separate Android editing app for every step I need when editing pics. 

I started using this one for lossless cropping but the huge value of the lossless cropping is offset by the inability to manage the dimensions and portion you are cropping. 

For a barebones cropping tool, I think that the core feature set should be the following:
1) manually set dimensions numerically
2) For values in #1, choose to anchor original  image to either (a) middle (default), or (b) a corner or side.

Simply being able to enter numerical dimensions would enable other things that people want without adding them specifically to the gui such as maintaining aspect ratio to original image, or switching aspect ratio while cropping.  Sure they might need to use a calculator to determine the new ratio but at least the ability would be there. 

#2  is pretty important although even just having 2 options (centre or one side) would do the trick if the image can be rotated inside or outside the app without degradation.
