### ISSUE TITLE
Addition of Rotation feature to llCrop (Loss Less)

### ISSUE THREAD

**Issue by adewararilwan** [k3b/LosslessJpgCrop#17]
### Repository
https://github.com/k3b/LosslessJpgCrop

###### What is llCrop (Loss Less)?
llCrop is an android application that allow user to remove unwanted part in a jpeg photos and ensure there is no loss of quality. 

### Component
My suggestion is on the 
- Photo editing interface

## Proposal
> llCrop is an application that is used to edit unwanted part in jpeg photos and still not loose its image quality.  Adding the proposed features will improve the  application.

- Rotation

### *Rotation*- 
I suggest the addiction of the rotation feature. The llCrop (Loss Less) is an application which is built for editing of image but currently the application lack the enabling of rotating image from side to side positions of choice.
I proposed the addition of the rotation feature that can easily allow users to rotate image from its original position to a preferred position.

# MOCKUP EXAMPLE
![Rotate](https://user-images.githubusercontent.com/48644964/58386349-7e59af80-7ff6-11e9-8036-725dd73c457c.jpg)

The image above is how the Rotation feature can look like when implemented that will allow users to be able to change the position of the image side by side.

- Rotation –
 These will be a very important feature that will improve the application. It will allow users to place image into any position of choice. 
For example: A user who edited an image, but not too comfortable with the way the image  is positioned, the user can simply click on the rotation feature and change image to preferred position of their choice.

### Conclusion
The feature when implemented will really improve the application, it will make the application to be more efficient and useful to users and will increase the users experience and the users-base.    

## My Github Profile
https://github.com/adewararilwan

[Update 20190527 by k3b] Removed feature request "add text" as this cannot be done lossless

**Comment by k3b** [comment]
This is not a general purpose photo editor, but an optimized app for lossless jpg operations.

Adding text cannot be done lossless

**Comment by k3b** [comment]
rotation will be available in next version 1.2
