### ISSUE TITLE
Save button not working, is gray

### ISSUE THREAD

**Issue by anonymous108** [k3b/LosslessJpgCrop#22]
Hello developer,

Please forgive me. Your app is not seeming to function. After I crop the image the way I like I press the button in the top right. A filename screen shows with a filing cabinet in the middle, I try to type the file name but the save button is grey and not able to be pressed.

I also try to remove the ':' character from the suggest filename but is not functioning for me still.

Why is not saving? Maybe is a bug? I am on the Nougat android. If you can help I would be very thankful. Having lossless crop is a clever idea, you must be clever to make this.

Thankyou for reading.

**Comment by k3b** [comment]
Have you tried to select a different folder? Your device may not allow to save to all folders. In my android-7.1 tablet i cannot save into sd-card-root-folder. (on my android-7.1 cellphone it works with root folder).

If this reply solves your problem, please close this ticket.

**Comment by k3b** [comment]
no reply within 6 weeks i assume this problem is solved. If not please reopen this ticket
