### ISSUE TITLE
Please add an option to resize pictures

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [k3b/LosslessJpgCrop#27]
Hello

This app is great.

May you please add an option to resize the whole picture instead of cropping it?

I think the simple approach to implementing it is let user only set wide or height, not both and so the app can keep the aspect ratio and change the size of the picture losslessly.

This option will be really great.

Thank you very much.

**Comment by k3b** [comment]
resizing cannot be done lossless and therefore is out of scope.

**Comment by 3j9fkyahunqoxwqu** [comment]
Oh, Thanks but how about resizing this way?

for ex. we have a high resolution picture, for example 32 MP. and that have 72 ppi, is resizing it in a way that we make the picture smaller in resolution, but using that extra resolution to increase the ppi of picture?

can this happen? 
is that somehow lossless? 

Thank you very much
