### ISSUE TITLE
Question as a user: how you achieved lossless jpeg manipulation

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [k3b/LosslessJpgCrop#28]
Sorry for using issues for asking questions, but i wanted to ask how you did this? (i don't have android programming experience, so i can't look at the code for finding out)

the actual question of me is this:

I use another app for photo editing and it has an option to choose output quality of jpeg.

Are cropping an image with setting the jpeg quality of that app to 100 percent is same as cropping it with your app or the procedure is different? 

I also suggest putting your answer in readme of this repo because that will be really useful for average user.

Thank you very much.

**Comment by k3b** [comment]
I use an existing opensource c++ library for this.

**Comment by 3j9fkyahunqoxwqu** [comment]
Oh, Thank you.
