### ISSUE TITLE
Failed to install on Pixel XL with LineageOS 17.1

### ISSUE THREAD

**Issue by eapo** [k3b/LosslessJpgCrop#30]
![Failed to install due to an unknown error 20201130-214854_F-Droid](https://user-images.githubusercontent.com/4000929/100663243-4bfce100-3356-11eb-892b-1d7d4f4c5d64.png)

17.1-20201125-NIGHTLY-marlin
3.18.137-lineageos-g64d0548
#1 Wed Nov 25 07:09:12 UTC 2020

**Comment by k3b** [comment]
without having more infos i donot know how to solve this issue. I have and having no linageos device and i donot know how to debug this.

**Comment by eapo** [comment]
The last version working amazingly well on Lineage 20. Thank you for the amazing work!
