### ISSUE TITLE
Display crop box coordinates and size

### ISSUE THREAD

**Issue by cunlem** [k3b/LosslessJpgCrop#35]
It would be useful to have XY offset of of top left corner of crop box displayed along with it's dimensions. One can get more predictable results by sticking to 8 or 16 multiples for offset and box size allows to target aspect ratio

**Comment by k3b** [comment]
related but not the same : #15

**Comment by k3b** [comment]
Will be available with next release :-)

**Comment by cunlem** [comment]
Awesome! I think I'll try to compile and test it in the meantime

**Comment by cunlem** [comment]
Very nice. I was able to achieve perfect crop on the first try:

![llcrop](https://user-images.githubusercontent.com/87859114/192170529-953cc290-f4ba-41dd-a68d-e2262edd87a3.jpg)

Thank you for this feature.

I have to admit it was a bit hard to set the right values by dragging the box. I think the next step would be putting those values inside four editable text boxes: two for (x, y) coordinates of top left corner (bottom right corner is immaterial) and two for box dimensions.

**Comment by k3b** [comment]
done.

available with next release 1.3
