### ISSUE TITLE
Dual-license to Apache license?

### ISSUE THREAD

**Issue by nicolas-raoul** [k3b/LosslessJpgCrop#36]
Happy New Year k3b!

I want to integrate a crop feature into our open source app (Wikimedia upload app), and re-using your smooth UI work would be ideal.

However, our app is Apache-license, so we can not include GNU-GPL code.

While I always license my desktop tools as GNU-GPL, most open source Android apps are Apache-license, so having this license would allow your code to be useful to more apps.

If you agree, it would be as simple as adding this text file to the root of the repository: https://www.apache.org/licenses/LICENSE-2.0.txt

Thank you for your consideration! :-)

**Comment by k3b** [comment]
Since Appache License does not require to open-source the derived work i do not want tho shift to Apache-license
