### ISSUE TITLE
App malfunctions when it's being rotated to landscape

### ISSUE THREAD

**Issue by iamowomizz** [k3b/LosslessJpgCrop#6]
DESCRIPTION
After cropping an image on the app and then I rotate the phone to land scape mode then click on save the photo doesn't get saved

STEPS
Open the app 
Select And crop a picture
Click on the save button by the top right corner on the app
Then rotate the app to landscape, then rename the photo and click on save

EXPECTED
After cropping an image on the app and then I rotate the phone to landscape mode then save the photo, I expect the photo to get saved on my phone and I should be able to view the photo

OBSERVATIONS
After cropping an image on the app and then I rotate the phone to landscape mode then save the photo on my phone, the photo doesn't get saved instead I get a broken photo which is not viewable

**Comment by k3b** [comment]
fixed in v1.0.2.190515
