### ISSUE TITLE
llCrop crashes in "save crop picture as" when filename contains illegal character

### ISSUE THREAD

**Issue by facebook-786** [k3b/LosslessJpgCrop#7]
# Project Information

* Repository: https://github.com/k3b/LosslessJpgCrop
* Project Name:  llCrop (Loss Less)

# Expected behavior
 

When I try to save the picture after crop, the picture should be saved and the saved picture should appear in the mobile phone gallery.

# Actual behavior

The application crashes when I try to save the picture to the cell phone storage

# How to reproduce

1-[Download ](https://f-droid.org/en/packages/de.k3b.android.lossless_jpg_crop/) the app and open it
2-Select any picture from mobile storage
3-Crop the image
4- Try saving the image in the phone by clicking Save button
5- see the bug 

* Browser/App version: Version 1.0.1.190507
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190512_144440](https://user-images.githubusercontent.com/50115498/57580858-e4c1c800-7463-11e9-8992-ddbc1b91c6ba.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>D/AndroidRuntime( 4900): Shutting down VM

E/AndroidRuntime( 4900): FATAL EXCEPTION: main

E/AndroidRuntime( 4900): Process: de.k3b.android.lossless_jpg_crop, PID: 4900

E/AndroidRuntime( 4900): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:image_1609_llcrop (1).jpg flg=0x43 }} to activity {de.k3b.android.lossless_jpg_crop/de.k3b.android.lossless_jpg_crop.CropAreasChooseActivity}: java.nio.charset.IllegalCharsetNameException: java.nio.charset.CharsetICU[UTF-8]

E/AndroidRuntime( 4900): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4005)

E/AndroidRuntime( 4900): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4048)

E/AndroidRuntime( 4900): 	at android.app.ActivityThread.access$1400(ActivityThread.java:177)

E/AndroidRuntime( 4900): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)

E/AndroidRuntime( 4900): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 4900): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 4900): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime( 4900): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 4900): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 4900): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime( 4900): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime( 4900): Caused by: java.nio.charset.IllegalCharsetNameException: java.nio.charset.CharsetICU[UTF-8]

E/AndroidRuntime( 4900): 	at java.nio.charset.Charset.checkCharsetName(Charset.java:201)

E/AndroidRuntime( 4900): 	at java.nio.charset.Charset.forName(Charset.java:295)

E/AndroidRuntime( 4900): 	at java.net.URLDecoder.decode(URLDecoder.java:60)

E/AndroidRuntime( 4900): 	at de.k3b.android.lossless_jpg_crop.CropAreasChooseActivity.toString(CropAreasChooseActivity.java:263)

E/AndroidRuntime( 4900): 	at de.k3b.android.lossless_jpg_crop.CropAreasChooseActivity.onOpenPublicOutputUriPickerResult(CropAreasChooseActivity.java:234)

E/AndroidRuntime( 4900): 	at de.k3b.android.lossless_jpg_crop.CropAreasChooseActivity.onActivityResult(CropAreasChooseActivity.java:321)

E/AndroidRuntime( 4900): 	at android.app.Activity.dispatchActivityResult(Activity.java:6441)

E/AndroidRuntime( 4900): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4001)

E/AndroidRuntime( 4900): 	... 10 more
</code></pre>

**Comment by phuyuk** [comment]
Same for me: Crash while saving, zero-length file created.
SM-P900, Lineage 13

**Comment by k3b** [comment]
Thanks for the error report.

    > java.nio.charset.IllegalCharsetNameException: java.nio.charset.CharsetICU[UTF-8]

* what locale (gui-language) are you using?
* have you edited a file that contains a non-utf-8 character in it-s filename or directory?

I have only tested with german and english filenames/directories

**Comment by k3b** [comment]
fixed in v1.0.2.190515

**Comment by facebook-786** [comment]
thanks u sir

**Comment by k3b** [comment]
@facebook-786: this was one of the most helpfull error-reports i ever received on github. It contains all infos i needed to fix the problem. well done.

**Comment by phuyuk** [comment]
Confirmed fixed with F-Droid build 1.0.2.190515. Thank you very much.

**Comment by facebook-786** [comment]
thanks u sir
